spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin
      authentication-database: admin
      database:  Productsdb


server:
  port: 9292
