version: '24.0.2'
services:
  mongodb:
    image: mongo
    ports:
      - 27018:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb